import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navigation from "./components/Nav/navigation";
import BackToTop from "./components/Nav/backToTop";
import Backdrop from "./components/Backdrop";
import ResumeSection from "./components/Resume/resumeSection";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased scroll-smooth overflow-x-hidden relative`}
      >
        <Backdrop />
        <Navigation />
        {children}
        <BackToTop />
        <div
          id="resume"
          className="relative w-full h-screen bg-gradient-to-tl from-purple-950 to-purple-600"
        >
          <div className="absolute bg-gradient-to-b from-purple-700 h-24 w-24 top-10 right-5 md:right-20 rounded-full"></div>
          <ResumeSection />
        </div>
      </body>
    </html>
  );
}
