import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navigation from "./components/Nav/navigation";
import BackToTop from "./components/Nav/backToTop";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased scroll-smooth overflow-x-hidden relative`}
      >
        <div className="absolute gap-3 right-2 md:right-40 top-0 flex">
          <div className=" bg-purple-500 w-14 md:w-20 h-[4.5rem] md:h-[30rem]  rounded-b-full opacity-50"></div>
          <div className=" bg-purple-800 w-20 h-[5rem] md:h-[40rem] hidden md:block rounded-b-full opacity-30"></div>
          <div className=" bg-fuchsia-500 w-20 h-[3rem] md:h-[30rem] hidden md:block rounded-b-full opacity-30"></div>
        </div>
        <Navigation />
        {children}
        <BackToTop />
      </body>
    </html>
  );
}
